version: '3'
services:

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  api-endpoint:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - REDIS_HOST=redis://redis:6379
